### PR TITLE
Add generalized_rps environment

### PR DESCRIPTION
**Pull request by afozk95**
Heaving read [this][issue] comment, I wanted to implement a generalized rock paper scissors environment. It expects two parameters, one for possible list of moves and one for relations between moves (e.g. rewards for agents given moves). For example one can create an environment for classic Rock Paper Scissors game with the following code:
```python
from pettingzoo.classic import rps_generalized_v1

rps_moves = ["ROCK", "PAPER", "SCISSORS"]
rps_relations = {
    ("ROCK", "ROCK"): (0, 0),
    ("ROCK", "PAPER"): (-1, 1),
    ("ROCK", "SCISSORS"): (1, -1),
    ("PAPER", "ROCK"): (1, -1),
    ("PAPER", "PAPER"): (0, 0),
    ("PAPER", "SCISSORS"): (-1, 1),
    ("SCISSORS", "ROCK"): (-1, 1),
    ("SCISSORS", "PAPER"): (1, -1),
    ("SCISSORS", "SCISSORS"): (0, 0),
}

env = rps_generalized_v1.env(rps_moves, rps_relations)
```

In order to create Rock Paper Scissors Lizard Spock environment, the following code can be used:
```python
from pettingzoo.classic import rps_generalized_v1

rpsls_moves = ["ROCK", "PAPER", "SCISSORS", "LIZARD", "SPOCK"]
rpsls_relations = {
    ("ROCK", "ROCK"): (0, 0),
    ("ROCK", "PAPER"): (-1, 1),
    ("ROCK", "SCISSORS"): (1, -1),
    ("ROCK", "LIZARD"): (1, -1),
    ("ROCK", "SPOCK"): (-1, 1),

    ("PAPER", "ROCK"): (1, -1),
    ("PAPER", "PAPER"): (0, 0),
    ("PAPER", "SCISSORS"): (-1, 1),
    ("PAPER", "LIZARD"): (-1, 1),
    ("PAPER", "SPOCK"): (1, -1),

    ("SCISSORS", "ROCK"): (-1, 1),
    ("SCISSORS", "PAPER"): (1, -1),
    ("SCISSORS", "SCISSORS"): (0, 0),
    ("SCISSORS", "LIZARD"): (1, -1),
    ("SCISSORS", "SPOCK"): (-1, 1),

    ("LIZARD", "ROCK"): (-1, 1),
    ("LIZARD", "PAPER"): (1, -1),
    ("LIZARD", "SCISSORS"): (-1, 1),
    ("LIZARD", "LIZARD"): (0, 0),
    ("LIZARD", "SPOCK"): (1, -1),

    ("SPOCK", "ROCK"): (1, -1),
    ("SPOCK", "PAPER"): (-1, 1),
    ("SPOCK", "SCISSORS"): (1, -1),
    ("SPOCK", "LIZARD"): (-1, 1),
    ("SPOCK", "SPOCK"): (0, 0),
}

env = rps_generalized_v1.env(rpsls_moves, rpsls_relations)
```

I am curious about your comments for the idea of adding generalized version of rock paper scissors environment to PettingZoo. Also, please feel free to give ideas about variable / function names and testing the new environment. Lastly, what do you feel about adding type annotations to code?

[issue]: https://github.com/PettingZoo-Team/PettingZoo/pull/384#issuecomment-850005293

### CODE REVIEW

**Comment by benblack769** [comment]
I'm glad you are so excited to contribute to PettingZoo!

Unfortunately, @rodrigodelazcano is already implementing the generalized rock paper scissors game I mentioned in the issue. He is modifying #384 to include it. In addition, we try to make config simple to use, and try to avoid having large dictionary inputs. So it is unlikely this will be merged as it is now. 

If you want to create a new PettingZoo environment, then we advise you create and test it in another repo. We would be happy to add it to a list of external environments. 

If you really want to include an environment in PettingZoo proper, please talk to us to discuss whether it is appropriate for the main repo.

**Comment by afozk95** [comment]
Thanks for the answer. If you think it makes sense to add my implementation as an external environment I can work on that. If yes, is there a guideline or an example I can follow? Otherwise, I will close this PR.

**Comment by benblack769** [comment]
So I am not claiming this is a valuable environment for the community. However, if you feel that it is, then you can make a 3rd party environment. 

If you want to make an environment that we definitely do think will be valuable to the community, then we can talk about environments we still wish to include in the pettingzoo ecosystem.

**Comment by justinkterry** [comment]
So there isn't a guideline, it's just a 3rd party repo with the environment in a way that it can be imported and passes tests. If you look at libraries that depend on PettingZoo there's several like that.

Also if you do create the repo please send me a link. We'll have a list of 3rd party environments with the new documentation website in a few months.

**Pull request closed without merging**
