### PR TITLE
issue 286

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
#286 already solved. I tested the seed test for the prospector env with more than 10000 cycles without any errors. 
I proceeded to include prospector env in the seed test.

### CODE REVIEW

**Comment by justinkterry** [comment]
Could you try it for 1 million to be safe?

**Comment by justinkterry** [comment]
If that's too much for your laptop message me

**Comment by benblack769** [comment]
I suspect this was solved by the pymunk update awhile back. It definitely failed consistently with only 10000 cycles back then.

**Comment by justinkterry** [comment]
And that's why I demanded we bump versions for new pymunk. LGTM.

**Pull request merged**
