### PR TITLE
Texas holdem pygame

### PR DESCRIPTION
**Pull request by Kyle-Sang**

### CODE REVIEW

**Comment by Kyle-Sang** [comment]
Texas_Holdem_Test

**Comment by Kyle-Sang** [comment]
Texas_Holdem_Test2

**Comment by Kyle-Sang** [comment]
There isn't a direct way to write to a Surface object, so the font is only available in human mode of the render.

**Comment by benblack769** [comment]
I belive the font rendering should work in rgb_array mode if `pygame.font.init()` is called..

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/123334743-87891380-d511-11eb-853c-42b9e28035fb.mp4

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/123334766-8e178b00-d511-11eb-91d8-f542ff342d3c.mp4

**Comment by Kyle-Sang** [comment]
Tell me when the colored chips are available, no limit holdem will look weird until then.

**Comment by justinkterry** [comment]
The window should change sizes depending on the number of players to remove all the empty space on the sides

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/123586476-c4276a00-d7b2-11eb-9d23-331f27c4d4f7.mp4

**Comment by justinkterry** [comment]
So this generally needs to be more compact for what we want to do with it:

-Move the piece stack off to the right side of each players cards
-Make the middle cards 2x3 instead of 1x6 to remove more empty space
-Make sure the spacing is even on all sides

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/124034839-b8fa5700-d9c9-11eb-9a26-755005b71767.mp4

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/124034851-bc8dde00-d9c9-11eb-9ab0-ee450241f132.mp4

**Comment by jkterry1** [comment]
Upload a new gif when you have it

**Comment by Kyle-Sang** [comment]
https://user-images.githubusercontent.com/78330032/125182842-86c5d200-e1df-11eb-8dab-b21be06c4303.mp4


https://user-images.githubusercontent.com/78330032/125182843-888f9580-e1df-11eb-9326-6b5268f53fd5.mp4

**Pull request merged**
