### PR TITLE
Rlcard version 1.0.3 and num players

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
- Fixed Dou Dizhu action/observation spaces
- Add extra players for rlcard envs
- Docs

### CODE REVIEW

**Comment by benblack769** [comment]
Generally looks good. I would put a few tests here https://github.com/PettingZoo-Team/PettingZoo/blob/master/test/all_parameter_combs.py#L26 with different numbers of players for all the games which support it.

**Comment by rodrigodelazcano** [comment]
> Generally looks good. I would put a few tests here https://github.com/PettingZoo-Team/PettingZoo/blob/master/test/all_parameter_combs.py#L26 with different numbers of players for all the games which support it.

Sure thing. I'll do that

**Comment by rodrigodelazcano** [comment]
https://github.com/datamllab/rlcard/pull/230 . PR for fixing extra players in some rlcard holdem games. I will push the tests ones this is solved

**Comment by rodrigodelazcano** [comment]
Tests for different number of players for rlcard envs have been added. Also the seed method for rlcard envs had to be modified. Please let me know if any more changes are needed.

**Comment by benblack769** [comment]
I am happy with all of these changes.

**Pull request merged**
