### PR TITLE
fixed crashes on headless server

### PR DESCRIPTION
**Pull request by weepingwillowben**
pistonball, KAZ and pursuit were crashing on my headless server due to pygame errors. 

This PR fixes it.

### CODE REVIEW

**Comment by MarioJayakumar** [comment]
Hey could you clarify what crash you were getting? The travis build is also a headless server but the only crash that was happening was that the bombardment test would take too long.

**Comment by weepingwillowben** [comment]
Yes it was a:

pygame.error: No available video device

error

**Comment by weepingwillowben** [comment]
Sorry, that was the wrong error. here is the error I am getting: 
pygame.error: video system not initialized

**Comment by MarioJayakumar** [comment]
I'll check this out locally, this weird because i only ever got the "video system not initialized" error when using pygame.pump on a closed environment or trying to render a closed environment

**Pull request merged**
