### PR TITLE
Added support for num_forests!=2 in mpe/simple_world_comm

### PR DESCRIPTION
**Pull request by vstark21**
Environment just supports num_forests=2 but not any other value you can see at this [line](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/simple_world_comm_v2.py#L9). So I have added the support for other values as well.

### CODE REVIEW

**Comment by justinkterry** [comment]
@weepingwillowben

**Comment by weepingwillowben** [comment]
I'll take a look at this soon

**Comment by weepingwillowben** [comment]
So I gave it a look over, and it generally looks good, it can handle edge cases and the logic all checks out. 

It would be preferable if this change also changed the associated documentation here: https://github.com/PettingZoo-Team/PettingZoo/blob/master/docs/mpe/simple_world_comm.md#arguments

**Comment by vstark21** [comment]
Changed the associated documentation as well.

**Comment by justinkterry** [comment]
Why is there a documentation change for pong in this?

**Comment by vstark21** [comment]
Change is in atari/pong_v1.py file, added a comment for assert statement for num_players==2or4. I missed mentioning it in the first comment.

**Comment by justinkterry** [comment]
Thanks a ton!

**Pull request merged**
